#!/usr/bin/env bash
Config_dir="$XDG_DATA_HOME/db-pm"
User="hiccup"
DL_Folder=~/Downloads
Pulse_conf=$Config_dir/pulseaudio.client.conf
Pulse_socket=/tmp/pulseaudio.socket
Pulse_cookie=/tmp/pulseaudio.cookie
Profile_name=$1
Profile=$2

if [ ! -d "$Profile" ]; then
  echo "Folder '$Profile' does not exist."
  exit 1
fi

# Confirm PulseAudio configuration file is in place
cat > $Pulse_conf <<- EOM
default-server = unix:/tmp/pulseaudio.socket
# Prevent a server running in the container
autospawn = no
daemon-binary = /bin/true
# Prevent the use of shared memory
enable-shm = false
EOM

# TODO: Add some error handling
pactl load-module module-native-protocol-unix socket=/tmp/pulseaudio.socket

docker run --rm \
    -e DISPLAY=$DISPLAY \
    -e XAUTHORITY=/home/$User/.Xauthority \
    -v $XAUTHORITY:/home/$User/.Xauthority \
    -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
    -v $Profile/:/home/$User/.config/BraveSoftware/Brave-Browser/Default/ \
    -v $Config_dir/Local\ State:/home/$User/.config/BraveSoftware/Brave-Browser/Local\ State \
    -v $DL_Folder:/home/hiccup/Downloads \
    --ipc=host \
    --user $(id -u):$(id -g) \
    --cap-drop=ALL \
    --security-opt seccomp="$Config_dir/seccomp.json" \
    --network="host" \
    --env PULSE_SERVER=unix:$Pulse_socket \
    --env PULSE_COOKIE=$Pulse_cookie \
    -v $Pulse_socket:$Pulse_socket \
    -v $Pulse_conf:/etc/pulse/client.conf \
    local/dbrave:v0.01 brave-browser --class="$Profile_name"
